# This is a basic workflow to help you get started with Actions

name: Scan OWASP ZAP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: OWASP ZAP Scan
  # You may pin to the exact commit or the version.
  # uses: zaproxy/action-baseline@acd8e997263688cb49cb5ff8247a4b2758c548ab
        uses: zaproxy/action-full-scan@v0.2.0
        with:
    # GitHub Token to create issues in the repository
    # Target URL
          target: https://preview.owasp-juice.shop
      - name: prueba
        run: ls /home/runner/work/Seminario-de-seguridad/Seminario-de-seguridad
      - name: comando-y-lectura
        run: |
              jq 'if .site[].alerts[].confidence == "3" then true else empty end' /home/runner/work/Seminario-de-seguridad/Seminario-de-seguridad/report_json.json > /home/runner/work/Seminario-de-seguridad/Seminario-de-seguridad/resp.txt
              if grep -q true "/home/runner/work/Seminario-de-seguridad/Seminario-de-seguridad/resp.txt"; then 
                echo mal
              fi
      
      #- name: deploy        
      #  uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
      #  with:
      #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #    heroku_app_name: seminario-seguridad #Must be unique in Heroku
      #    heroku_email: german.ospina-q@mail.escuelaing.edu.co

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: seminario-seguridad
          heroku_email: german.ospina-q@mail.escuelaing.edu.co


